---
title: "Biofilm vs initial water community"
author: "Sven Tobias-Hunefeldt"
date: "02/04/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Set up
Import data and refine as done using the set up script

```{r load packages}

library(ggpubr)
library(vegan)
library(ggplot2)
library(Rmisc)
library(phyloseq)
library(tidyr)
library(dplyr)



```
```{r Refine colours and shapes}
#Refine colours
cbbPalette <- c("black",
                "red",
                "navy", 
                "green", 
                "magenta",
                "forestgreen",
                "turquoise")

Mesh_Palette = c("Enclosed" = "#000000",
                 "Non-enclosed" = "#E69F00")

```
#Supplementary Figure
```{r Extract and run prokayotic comparisons}
#Get pristine verison of phyloseq
Phyloseq_Biofilm_16S = Phyloseq_Biofilm_16S_v0

#Extract otu table
OTU1 = as(otu_table(Phyloseq_Biofilm_16S), "matrix")

#Make sure rows are samples and columns are the different taxa (ASVs in this case)
if(taxa_are_rows(Phyloseq_Biofilm_16S)){OTU1 <- t(OTU1)}

#Convert to a dataframe for later manipulation
OTUdf = as.data.frame(OTU1)

#Run bray dissimilarity matrix - we want quantitative hence we turn off binary
Braydf = vegdist(OTUdf, method = "bray", binary = FALSE)

#write.csv(as.matrix(Braydf), "Bray_Diss_16S.csv")

```
```{r Reformat prokaryotic for downstream analysis}

#Make into readable form (wide)
Braydf_wide = as.data.frame(as.matrix(Braydf))
Braydf_wide$Sample_ID = rownames(as.data.frame(as.matrix(Braydf))) #Make rownames another column
colnames(Braydf_wide) #Check to make sure rename worked
Braydf_long = reshape2::melt(Braydf_wide, id.vars = "Sample_ID") #Make df into long format

#Rename y axis so more meaningful
colnames(Braydf_long)[3] <- "Bray_dissimilarity"
colnames(Braydf_long)[2] <- "Var2" 
colnames(Braydf_long)[1] <- "Var1" 


#Remove self-comparisons
Braydf_long = Braydf_long %>%
    dplyr::filter(as.character(Var1) != as.character(Var2)) %>%
    dplyr::mutate_if(is.factor,
              as.character)
Temporary_df = Braydf_long 

#remove replicate information
Temporary_df$Var1 = gsub("za","", Temporary_df$Var1)
Temporary_df$Var1 = gsub("zb","", Temporary_df$Var1)
Temporary_df$Var1 = gsub("zc","", Temporary_df$Var1)
Temporary_df$Var1 = gsub("zd","", Temporary_df$Var1)

#Determine source of sample
Temporary_df$Substrate = NA
for (i in 1:nrow(Temporary_df)) {
if (grepl("p", Temporary_df$Var1[i]) == T){
  Temporary_df$Substrate[i] = "Wood"
} else if (grepl("a", Temporary_df$Var1[i]) == T){
  Temporary_df$Substrate[i] = "Plastic"
} else if (grepl("g", Temporary_df$Var1[i]) == T){
  Temporary_df$Substrate[i] = "Glass"
} else if (grepl("t", Temporary_df$Var1[i]) == T){
  Temporary_df$Substrate[i] = "Tile"
} else if (grepl("me", Temporary_df$Var1[i]) == T){
  Temporary_df$Substrate[i] = "Mesh"
} else if (grepl("ws", Temporary_df$Var1[i]) == T){
  Temporary_df$Substrate[i] = "Water"
}
  i=i+1
}

#Determine when sample was collected
Temporary_df$Sample_time = NA
for (i in 1:nrow(Temporary_df)) {
if (grepl("0", Temporary_df$Var1[i]) == T){
  Temporary_df$Sample_time[i] = "0"
} else if (grepl("1", Temporary_df$Var1[i]) == T){
  Temporary_df$Sample_time[i] = "7"
} else if (grepl("2", Temporary_df$Var1[i]) == T){
  Temporary_df$Sample_time[i] = "14"
} else if (grepl("3", Temporary_df$Var1[i]) == T){
  Temporary_df$Sample_time[i] = "19"
} else if (grepl("4", Temporary_df$Var1[i]) == T){
  Temporary_df$Sample_time[i] = "28"
} else if (grepl("5", Temporary_df$Var1[i]) == T){
  Temporary_df$Sample_time[i] = "42"
} else if (grepl("6", Temporary_df$Var1[i]) == T){
  Temporary_df$Sample_time[i] = "56"
}
  i=i+1
}

#Determine enclosure status of sample
Temporary_df$Mesh_status = NA
for (i in 1:nrow(Temporary_df)) {
if (grepl("e", Temporary_df$Var1[i]) == T){
  Temporary_df$Mesh_status[i] = "Non-enclosed"
} else if (grepl("m", Temporary_df$Var1[i]) == T){
  Temporary_df$Mesh_status[i] = "Enclosed"
} else if (grepl("ws", Temporary_df$Var1[i]) == T){
  Temporary_df$Mesh_status[i] = "Water"
}
  i=i+1
}

Temporary_df$StageofBiofilm = NA
for (i in 1:nrow(Temporary_df)) {
if (grepl("1", Temporary_df$Var1[i]) == T | grepl("2", Temporary_df$Var1[i]) == T){
  Temporary_df$StageofBiofilm[i] = "Early"
} else if (grepl("3", Temporary_df$Var1[i]) == T | grepl("4", Temporary_df$Var1[i]) == T | grepl("5", Temporary_df$Var1[i]) == T | grepl("6", Temporary_df$Var1[i]) == T){
  Temporary_df$StageofBiofilm[i] = "Late"
} 
  i=i+1
}

Temporary_df_16S_v0 = Temporary_df
Temporary_df_16S = Temporary_df_16S_v0
```
```{r Extract and run rukayotic comparisons}
#Get pristine verison of phyloseq
Phyloseq_Biofilm_18S = Phyloseq_Biofilm_18S_v0

#Extract otu table
OTU1 = as(otu_table(Phyloseq_Biofilm_18S), "matrix")

#Make sure rows are samples and columns are the different taxa (ASVs in this case)
if(taxa_are_rows(Phyloseq_Biofilm_18S)){OTU1 <- t(OTU1)}

#Convert to a dataframe for later manipulation
OTUdf = as.data.frame(OTU1)

#Run bray dissimilarity matrix - we want quantitative hence we turn off binary
Braydf = vegdist(OTUdf, method = "bray", binary = FALSE)

#write.csv(as.matrix(Braydf), "Bray_Diss_18S.csv")

```
```{r Reformat eukaryotic for downstream analysis}

#Make into readable form (wide)
Braydf_wide = as.data.frame(as.matrix(Braydf))
Braydf_wide$Sample_ID = rownames(as.data.frame(as.matrix(Braydf))) #Make rownames another column
colnames(Braydf_wide) #Check to make sure rename worked
Braydf_long = reshape2::melt(Braydf_wide, id.vars = "Sample_ID") #Make df into long format

#Rename y axis so more meaningful
colnames(Braydf_long)[3] <- "Bray_dissimilarity"
colnames(Braydf_long)[2] <- "Var2" 
colnames(Braydf_long)[1] <- "Var1" 


#Remove self-comparisons
Braydf_long = Braydf_long %>%
    dplyr::filter(as.character(Var1) != as.character(Var2)) %>%
    dplyr::mutate_if(is.factor,
              as.character)
Temporary_df = Braydf_long 

#remove replicate information
Temporary_df$Var1 = gsub("za","", Temporary_df$Var1)
Temporary_df$Var1 = gsub("zb","", Temporary_df$Var1)
Temporary_df$Var1 = gsub("zc","", Temporary_df$Var1)
Temporary_df$Var1 = gsub("zd","", Temporary_df$Var1)

#Determine source of sample
Temporary_df$Substrate = NA
for (i in 1:nrow(Temporary_df)) {
if (grepl("p", Temporary_df$Var1[i]) == T){
  Temporary_df$Substrate[i] = "Wood"
} else if (grepl("a", Temporary_df$Var1[i]) == T){
  Temporary_df$Substrate[i] = "Plastic"
} else if (grepl("g", Temporary_df$Var1[i]) == T){
  Temporary_df$Substrate[i] = "Glass"
} else if (grepl("t", Temporary_df$Var1[i]) == T){
  Temporary_df$Substrate[i] = "Tile"
} else if (grepl("me", Temporary_df$Var1[i]) == T){
  Temporary_df$Substrate[i] = "Mesh"
} else if (grepl("ws", Temporary_df$Var1[i]) == T){
  Temporary_df$Substrate[i] = "Water"
}
  i=i+1
}

#Determine when sample was collected
Temporary_df$Sample_time = NA
for (i in 1:nrow(Temporary_df)) {
if (grepl("0", Temporary_df$Var1[i]) == T){
  Temporary_df$Sample_time[i] = "0"
} else if (grepl("1", Temporary_df$Var1[i]) == T){
  Temporary_df$Sample_time[i] = "7"
} else if (grepl("2", Temporary_df$Var1[i]) == T){
  Temporary_df$Sample_time[i] = "14"
} else if (grepl("3", Temporary_df$Var1[i]) == T){
  Temporary_df$Sample_time[i] = "19"
} else if (grepl("4", Temporary_df$Var1[i]) == T){
  Temporary_df$Sample_time[i] = "28"
} else if (grepl("5", Temporary_df$Var1[i]) == T){
  Temporary_df$Sample_time[i] = "42"
} else if (grepl("6", Temporary_df$Var1[i]) == T){
  Temporary_df$Sample_time[i] = "56"
}
  i=i+1
}

#Determine enclosure status of sample
Temporary_df$Mesh_status = NA
for (i in 1:nrow(Temporary_df)) {
if (grepl("e", Temporary_df$Var1[i]) == T){
  Temporary_df$Mesh_status[i] = "Non-enclosed"
} else if (grepl("m", Temporary_df$Var1[i]) == T){
  Temporary_df$Mesh_status[i] = "Enclosed"
} else if (grepl("ws", Temporary_df$Var1[i]) == T){
  Temporary_df$Mesh_status[i] = "Water"
}
  i=i+1
}

Temporary_df$StageofBiofilm = NA
for (i in 1:nrow(Temporary_df)) {
if (grepl("1", Temporary_df$Var1[i]) == T){
  Temporary_df$StageofBiofilm[i] = "Early"
} else if (grepl("2", Temporary_df$Var1[i]) == T | grepl("3", Temporary_df$Var1[i]) == T | grepl("4", Temporary_df$Var1[i]) == T | grepl("5", Temporary_df$Var1[i]) == T | grepl("6", Temporary_df$Var1[i]) == T){
  Temporary_df$StageofBiofilm[i] = "Late"
} 
  i=i+1
}

Temporary_df_18S_v0 = Temporary_df
Temporary_df_18S = Temporary_df_18S_v0
```
```{r Combine prokaryotic and eukaryotic comparisons}
Temporary_df_16S_v0$Sequencing = as.factor("Prokaryotes")
Temporary_df_18S_v0$Sequencing = as.factor("Eukaryotes")

Temporary_df = rbind(Temporary_df_16S_v0, Temporary_df_18S_v0)
Temporary_df_v0 = Temporary_df


```
```{r Subset and plot}

#Subset to useable ones
Temporary_df = subset(Temporary_df_v0, 
                      Substrate!= "Mesh")

#Subset to only those comparing water to other communities
Temporary_df_2 = data.frame()
y = 1
for (i in 1:nrow(Temporary_df)) {
if (grepl("am", Temporary_df$Var1[i]) == T && grepl("ws", Temporary_df$Var2[i]) == T){
  Temporary_df_2 = rbind(Temporary_df_2, Temporary_df[i,])
  y = y+1
} else if (grepl("ae", Temporary_df$Var1[i]) == T && grepl("ws", Temporary_df$Var2[i]) == T){
  Temporary_df_2 = rbind(Temporary_df_2, Temporary_df[i,])
  y = y+1
} else if (grepl("gm", Temporary_df$Var1[i]) == T && grepl("ws", Temporary_df$Var2[i]) == T){
  Temporary_df_2 = rbind(Temporary_df_2, Temporary_df[i,])
  y = y+1
} else if (grepl("ge", Temporary_df$Var1[i]) == T && grepl("ws", Temporary_df$Var2[i]) == T){
  Temporary_df_2 = rbind(Temporary_df_2, Temporary_df[i,])
  y = y+1
} else if (grepl("pm", Temporary_df$Var1[i]) == T && grepl("ws", Temporary_df$Var2[i]) == T){
  Temporary_df_2 = rbind(Temporary_df_2, Temporary_df[i,])
  y = y+1
} else if (grepl("pe", Temporary_df$Var1[i]) == T && grepl("ws", Temporary_df$Var2[i]) == T){
  Temporary_df_2 = rbind(Temporary_df_2, Temporary_df[i,])
  y = y+1
} else if (grepl("tm", Temporary_df$Var1[i]) == T && grepl("ws", Temporary_df$Var2[i]) == T){
  Temporary_df_2 = rbind(Temporary_df_2, Temporary_df[i,])
  y = y+1
} else if (grepl("te", Temporary_df$Var1[i]) == T && grepl("ws", Temporary_df$Var2[i]) == T){
  Temporary_df_2 = rbind(Temporary_df_2, Temporary_df[i,])
  y = y+1
}
  i=i+1
}

#Make sure it worked
Temporary_df_2


#Subset to only those comparing to initial water
Temporary_df_2.1 = data.frame()
y = 1
for (i in 1:nrow(Temporary_df_2)) {
if (grepl("1", Temporary_df_2$Var1[i]) == T && grepl("0", Temporary_df_2$Var2[i]) == T){
  Temporary_df_2.1 = rbind(Temporary_df_2.1, Temporary_df_2[i,])
  y = y+1
} else if (grepl("2", Temporary_df_2$Var1[i]) == T && grepl("0", Temporary_df_2$Var2[i]) == T){
  Temporary_df_2.1 = rbind(Temporary_df_2.1, Temporary_df_2[i,])
  y = y+1
} else if (grepl("3", Temporary_df_2$Var1[i]) == T && grepl("0", Temporary_df_2$Var2[i]) == T){
  Temporary_df_2.1 = rbind(Temporary_df_2.1, Temporary_df_2[i,])
  y = y+1
} else if (grepl("4", Temporary_df_2$Var1[i]) == T && grepl("0", Temporary_df_2$Var2[i]) == T){
  Temporary_df_2.1 = rbind(Temporary_df_2.1, Temporary_df_2[i,])
  y = y+1
} else if (grepl("5", Temporary_df_2$Var1[i]) == T && grepl("0", Temporary_df_2$Var2[i]) == T){
  Temporary_df_2.1 = rbind(Temporary_df_2.1, Temporary_df_2[i,])
  y = y+1
} else if (grepl("6", Temporary_df_2$Var1[i]) == T && grepl("0", Temporary_df_2$Var2[i]) == T){
  Temporary_df_2.1 = rbind(Temporary_df_2.1, Temporary_df_2[i,])
  y = y+1
} 
  i=i+1
}

#Make sure it worked
Temporary_df_2.1

#Summarise for plotting
Temporary_df_2 = summarySE(Temporary_df_2.1, measurevar="Bray_dissimilarity", groupvars=c("Sample_time", "Substrate", "Mesh_status", "Sequencing"))

#Reorder for plotting
Temporary_df_2$Sample_time = factor(Temporary_df_2$Sample_time, 
                                      levels = c(7,14,19,28,42,56))
Temporary_df_2$Substrate <- factor(Temporary_df_2$Substrate,
                         levels=c("Plastic", "Glass", "Tile", "Wood"))
#Plot
SupplementaryFigure4 = ggplot(Temporary_df_2, aes(x= as.numeric(as.character(Sample_time)), y = Bray_dissimilarity, colour = Mesh_status, group = Mesh_status)) + 
  geom_line(lwd = 1)+
      geom_errorbar(aes(ymin=(Bray_dissimilarity-se), 
                    ymax=(Bray_dissimilarity+se),
                    colour = Mesh_status),
                position=pd)+
  facet_grid(Substrate ~ Sequencing)+
  scale_color_manual(values = Mesh_Palette)+
  ylab("Bray-Curtis dissimilarity")+
  xlab("Time (days)")+
  labs(colour = "Condition")+
  theme_bw()+
  My_Theme
#Check for errors 
SupplementaryFigure4

#Save plot
pdf("~/Desktop/Biofilm_project/Analysis/Clean_Thesis_Code/Figures/SupplementaryFigure4_InitialWatervsBiofilm.pdf", width = 16, height = 6.66)
SupplementaryFigure4
dev.off()
```


```{r Calculate means}
test_mean = Temporary_df_2 %>% 
  group_by(Sequencing) %>% 
  dplyr::summarise(mean_val = mean(Bray_dissimilarity), sd = sd(Bray_dissimilarity))
print(test_mean)

#Mean difference between prokaryotic and eukaryotic dissimilarity
test_mean$mean_val[2] - test_mean$mean_val[1]

test_mean = Temporary_df_2 %>% 
  group_by(Sample_time,
           Sequencing) %>% 
  dplyr::summarise(mean_val = mean(Bray_dissimilarity), sd = sd(Bray_dissimilarity))
print(test_mean)

#Differences between prokaryotic D7 and D56
test_mean$mean_val[11] - test_mean$mean_val[1]

test_mean = Temporary_df_2 %>% 
  group_by(Sample_time, 
           #Substrate, 
           Mesh_status, 
           Sequencing
           ) %>% 
  dplyr::summarise(mean_val = mean(Bray_dissimilarity), sd = sd(Bray_dissimilarity))
print(test_mean)

```
```{r Statistics }

wilcox.test(Temporary_df_2$Bray_dissimilarity ~ Temporary_df_2$Mesh_status, p.adjust.method = "bonferroni")
kruskal.test(Temporary_df_2$Bray_dissimilarity, Temporary_df_2$Sample_time, p.adjust.method = "bonferroni")
kruskal.test(Temporary_df_2$Bray_dissimilarity, Temporary_df_2$Substrate, p.adjust.method = "bonferroni")
wilcox.test(Temporary_df_2$Bray_dissimilarity ~ Temporary_df_2$Sequencing, p.adjust.method = "bonferroni")
#Significant differences for sample_time and sequencing


cor.test(Temporary_df_2$Bray_dissimilarity, as.numeric(as.character(Temporary_df_2$Sample_time)),  method = "s")

####Prokaryotes####
Temporary_df_2_Prok = subset(Temporary_df_2, Sequencing == "Prokaryotes")
wilcox.test(Temporary_df_2_Prok$Bray_dissimilarity ~ Temporary_df_2_Prok$Mesh_status, p.adjust.method = "bonferroni")
kruskal.test(Temporary_df_2_Prok$Bray_dissimilarity, Temporary_df_2_Prok$Sample_time, p.adjust.method = "bonferroni")
kruskal.test(Temporary_df_2_Prok$Bray_dissimilarity, Temporary_df_2_Prok$Substrate, p.adjust.method = "bonferroni")
cor.test(Temporary_df_2_Prok$Bray_dissimilarity, as.numeric(as.character(Temporary_df_2_Prok$Sample_time)),  method = "s")

####Eukaryotes####
Temporary_df_2_Euk = subset(Temporary_df_2, Sequencing == "Eukaryotes")
wilcox.test(Temporary_df_2_Euk$Bray_dissimilarity ~ Temporary_df_2_Euk$Mesh_status, p.adjust.method = "bonferroni")
kruskal.test(Temporary_df_2_Euk$Bray_dissimilarity, Temporary_df_2_Euk$Sample_time, p.adjust.method = "bonferroni")
kruskal.test(Temporary_df_2_Euk$Bray_dissimilarity, Temporary_df_2_Euk$Substrate, p.adjust.method = "bonferroni")
cor.test(Temporary_df_2_Euk$Bray_dissimilarity, as.numeric(as.character(Temporary_df_2_Euk$Sample_time)),  method = "s")

```